site_name: IMLS WIFISESS
nav:
    - Home: index.md
    - Repositories: repositories.md
    - Hardware:
      - Pi: hardware/pi.md
      - Wifi Adapters: hardware/wifi.md
    - Setup:
      - Bootstrap: setup/bootstrap.md
      - Playbook: setup/playbook.md
    - Software:
      - Initial Configuration: software/input-initial-configuration.md
      - Find Wifi Hardware: software/find-ralink.md
      - Session Counter: software/session-counter.md
    - Server Stack:
      - api.data.gov: stack/apidatagov.md
      - ReVal (Rabbit): stack/reval.md
      - Directus: stack/directus.md
    - Querying Data: 
      - Obtain a key: queries/obtainkey.md
      - Test your key: queries/testkey.md
      - Using GraphQL: queries/usinggql.md
      - Using REST: queries/viarest.md
      - Summary: queries/summary.md

theme: readthedocs
